# Generated by Django 6.0.6 on 2026-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'User have already exists!'}, max_length=150, null=True, unique=True),
        ),
    ]
