# Generated by Django 6.0.6 on 2026-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesselement',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='AccessRules',
        ),
        migrations.DeleteModel(
            name='BusinessElement',
        ),
    ]
