# Generated by Django 6.0.6 on 2026-06-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Business Element',
                'verbose_name_plural': 'Business Elements',
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='AccessRules',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20)),
                ('can_read', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessrules', to='system_console.businesselement')),
            ],
            bases=('common.basemodel',),
        ),
    ]
